services:
  iptv-toolkit:
    container_name: "IPTV-Toolkit"
    image: ${IMAGE_NAMESPACE:-losenmann}/${IMAGE_REPO:-iptv-toolkit}:${IMAGE_VERSION:-latest}
    hostname: iptv-toolkit
    command: ["-S", "-U", "-W"]
    network_mode: host
    expose:
      - 4022
      - 4023
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - path: ./global.env
        required: true
      - path: ./../testing/testing.env
        required: false
    environment:
      - IPTVTOOLKIT_EPG=${IPTVTOOLKIT_EPG:-}
      - IPTVTOOLKIT_EPG_DST=${IPTVTOOLKIT_EPG_DST:-/www/iptv-toolkit/tvguide}
      - IPTVTOOLKIT_PLAYLIST=${IPTVTOOLKIT_PLAYLIST:-}
      - IPTVTOOLKIT_PLAYLIST_DST=${IPTVTOOLKIT_PLAYLIST_DST:-/www/iptv-toolkit/playlist}
      - IPTVTOOLKIT_PLAYLIST_EMBED_EPG=${IPTVTOOLKIT_PLAYLIST_EMBED_EPG:-}
      - IPTVTOOLKIT_PLAYLIST_UDPXY=${IPTVTOOLKIT_PLAYLIST_UDPXY:-}
      - IPTVTOOLKIT_WEB_PORT=${IPTVTOOLKIT_WEB_PORT:-4023}
      - IPTVTOOLKIT_WEB_PATH=${IPTVTOOLKIT_WEB_PATH:-/www/iptv-toolkit}
      - IPTVTOOLKIT_CRONTAB=${IPTVTOOLKIT_CRONTAB:-30 6 * * *}
    labels:
      - traefik.enable=true
      - traefik.http.routers.iptv-toolkit.entrypoints=https
      - traefik.http.routers.iptv-toolkit.rule=Host(`${IPTVTOOLKIT_CTR_HOST:-}`)
      - traefik.http.routers.iptv-toolkit.tls=true
      - traefik.http.services.iptv-toolkit.loadbalancer.server.port=4023
      - traefik.docker.network=network-proxy
    tty: true
    restart: on-failure:3