services:
  iptv-toolkit:
    container_name: "IPTV-Toolkit"
    image: losenmann/iptv-toolkit:latest
    network_mode: host
    expose:
      - 4022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      IPTVTOOLKIT_PLAYLIST: "http://example.com/playlist.m3u"
      IPTVTOOLKIT_EPG: "http://example.com/epg.zip"
    labels:
      - traefik.enable=true
      - traefik.http.routers.iptv-toolkit.tls=true
      - traefik.http.routers.iptv-toolkit.entrypoints=https
      - traefik.http.routers.iptv-toolkit.rule=Host(`${IPTVTOOLKIT_HOST:-iptv.foo.bar}`)
      - traefik.http.services.iptv-toolkit.loadbalancer.server.port=4022
    tty: true
    restart: always
