version: "3.9"
services:
  iptv-toolkit:
    container_name: "IPTV-Toolkit"
    image: "losenmann/iptv-toolkit:latest"
    networks:
      - network-multicast
    expose:
      - 4022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - EPG_URL="http://localhost/epg.xml"
      - PLAYLIST_URL="http://localhost/playlist.m3u"
      - PLAYLIST_TVG_URL="http://localhost/epg.xml"
      - PLAYLIST_UDPXY_URL="http://udpxy.local:4022"
    tty: true
    restart: on-failure:3

networks:
  network-multicast:
    name: "network-multicast"
    driver: "macvlan"
    driver_opts:
      parent: "eth0"
    ipam:
      config:
        - subnet: "192.168.8.0/24"
          gateway: "192.168.8.1"
          ip_range: "192.168.8.24/29"