---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptv-toolkit
  labels:
    app: iptv-toolkit
    name: iptv-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iptv-toolkit
      task: iptv-toolkit
  template:
    metadata:
      labels:
        app: iptv-toolkit
        task: iptv-toolkit
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      containers:
        - name: iptv-toolkit
          image: losenmann/iptv-toolkit:latest
          args:
            - -S
            - -U
            - -W
          ports:
            - name: udpxy
              containerPort: 4022
            - name: web
              containerPort: 4023
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "75m"
              memory: "96Mi"
          envFrom:
            - configMapRef:
              name: iptv-toolkit-configmap
          volumeMounts:
            - name: time-config
              mountPath: /etc/localtime
              readOnly: true
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
      volumes:
        - name: time-config
          hostPath:
            path: /etc/localtime
            type: File
        - name: tz-config
          hostPath:
            path: /etc/timezone
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: iptv-toolkit-service
spec:
  ports:
    - name: web
      port: 4023
    - name: udpxy
      port: 4022
  selector:
    app: iptv-toolkit
    task: iptv-toolkit

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iptv-toolkit-ingress
spec:
  rules:
    - host: "foo.bar.com"
      http:
      paths:
        - pathType: Prefix
          path: /files
          backend:
            service:
              name: iptv-toolkit-service
              port:
                number: 4023
        - pathType: Prefix
          path: /udp
          backend:
            service:
              name: iptv-toolkit-service
              port:
                number: 4022