---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iptv-toolkit-configmap
data:
  IPTVTOOLKIT_EPG: ""
  IPTVTOOLKIT_EPG_DST: "/www/iptv-toolkit/tvguide"
  IPTVTOOLKIT_PLAYLIST: ""
  IPTVTOOLKIT_PLAYLIST_DST: "/www/iptv-toolkit/playlist"
  IPTVTOOLKIT_PLAYLIST_EMBED_EPG: ""
  IPTVTOOLKIT_PLAYLIST_UDPXY: ""
  IPTVTOOLKIT_WEB_PORT: "4023"
  IPTVTOOLKIT_WEB_PATH: "/www/iptv-toolkit"
  IPTVTOOLKIT_CRONTAB: "30 6 * * *"