---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptv-toolkit
  labels:
    app: iptv-toolkit
    name: iptv-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iptv-toolkit
      task: iptv-toolkit
  template:
    metadata:
      labels:
        app: iptv-toolkit
        task: iptv-toolkit
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      containers:
        - name: iptv-toolkit
          image: losenmann/iptv-toolkit:latest
          ports:
            - containerPort: 4022
          env:
            - name: IPTVTOOLKIT_EPG
              value: "http://localhost/epg.xml"
            - name: IPTVTOOLKIT_PLAYLIST
              value: "http://localhost/playlist.m3u"
            - name: IPTVTOOLKIT_PLAYLIST_EMBED_EPG
              value: "http://localhost/epg.xml"
            - name: IPTVTOOLKIT_PLAYLIST_UDPXY
              value: "http://udpxy.local:4022"
---
apiVersion: v1
kind: Service
metadata:
  name: iptv-toolkit-service
spec:
  ports:
    - name: web
      port: 4022
  selector:
    app: iptv-toolkit
    task: iptv-toolkit

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: iptv-toolkit-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`iptv.example.com`)
      kind: Rule
      services:
        - name: iptv-toolkit-service
          port: 4022
