remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: "IPTV Toolkit"
description: "A set of tools for working with IPTV services: Playlists, EPG, UDPXY"
show_downloads: true