FROM debian:sid-20250520-slim AS debian
ARG TARGETOS \
    TARGETARCH \
    PKG_VERSION
RUN apt update && apt install -y --no-install-recommends make build-essential dpkg-dev dh-make git
WORKDIR /opt/src
COPY . /opt/src
RUN make build-deb

FROM scratch AS pkg
COPY --from=debian /opt/src/pkg/debbuild/*.deb /
